package de.citybuild.core.generator;

import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.World;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Random;
import java.util.Set;
import java.util.logging.Logger;

/**
 * Digs rivers and lakes into the terrain generated by {@link TerrainGenerator}.
 *
 * <p>Rivers flow from map-edge start points toward lower terrain, guided by a
 * Simplex Noise gradient.  Lakes are placed as noise-warped ellipses.
 * All water blocks are recorded so that {@link RoadGenerator} can build bridges
 * where roads cross water.</p>
 */
public class WaterGenerator {

    private static final int RIVER_COUNT_MIN = 3;
    private static final int RIVER_COUNT_MAX = 5;
    private static final int LAKE_COUNT_MIN  = 4;
    private static final int LAKE_COUNT_MAX  = 8;

    private static final int RIVER_WIDTH_MIN = 4;
    private static final int RIVER_WIDTH_MAX = 8;
    private static final int RIVER_DEPTH_MIN = 2;
    private static final int RIVER_DEPTH_MAX = 4;

    private static final int LAKE_RADIUS_MIN = 15;
    private static final int LAKE_RADIUS_MAX = 40;
    private static final int LAKE_DEPTH_MIN  = 3;
    private static final int LAKE_DEPTH_MAX  = 6;
    private static final int LAKE_MIN_DIST   = 300;

    private static final int CITY_POND_RADIUS_MIN = 8;
    private static final int CITY_POND_RADIUS_MAX = 12;

    /** All XZ positions that contain water — used by RoadGenerator. */
    private final Set<Long> waterBlocks = new HashSet<>();

    private final Random rng;
    private final SimplexNoise warpNoise;
    private final TerrainGenerator terrain;

    /**
     * Creates a new WaterGenerator.
     *
     * @param seed    random seed
     * @param terrain the already-computed TerrainGenerator (for height queries)
     */
    public WaterGenerator(long seed, TerrainGenerator terrain) {
        this.rng       = new Random(seed ^ 0xABCDEF0123456789L);
        this.warpNoise = new SimplexNoise(seed ^ 0x1234567890ABCDEFL);
        this.terrain   = terrain;
    }

    /**
     * Generates rivers from the map edge toward the centre and places all
     * corresponding blocks (water, gravel bed, sand banks) in the world.
     *
     * <p>Must be called on the main server thread.</p>
     *
     * @param world     target world
     * @param mapRadius half-side of the generated region in blocks
     */
    public void generateRivers(World world, int mapRadius) {
        Logger log = Bukkit.getServer().getLogger();
        int riverCount = RIVER_COUNT_MIN + rng.nextInt(RIVER_COUNT_MAX - RIVER_COUNT_MIN + 1);

        for (int r = 0; r < riverCount; r++) {
            // Random start angle → position on the map edge
            double angle = rng.nextDouble() * 2 * Math.PI;
            int startX = (int) (Math.cos(angle) * (mapRadius - 100));
            int startZ = (int) (Math.sin(angle) * (mapRadius - 100));
            int width  = RIVER_WIDTH_MIN + rng.nextInt(RIVER_WIDTH_MAX - RIVER_WIDTH_MIN + 1);

            carveRiver(world, startX, startZ, mapRadius, width);
        }
        log.info("[WaterGenerator] Rivers generated.");
    }

    /**
     * Generates lakes scattered around the map plus one city pond near (0,0).
     *
     * <p>Must be called on the main server thread.</p>
     *
     * @param world     target world
     * @param mapRadius half-side of the generated region in blocks
     */
    public void generateLakes(World world, int mapRadius) {
        Logger log = world.getServer().getLogger();
        int lakeCount = LAKE_COUNT_MIN + rng.nextInt(LAKE_COUNT_MAX - LAKE_COUNT_MIN + 1);

        // City pond near origin
        int pondRadius = CITY_POND_RADIUS_MIN + rng.nextInt(CITY_POND_RADIUS_MAX - CITY_POND_RADIUS_MIN + 1);
        int pondX = rng.nextInt(60) - 30;
        int pondZ = rng.nextInt(60) - 30;
        carveLake(world, pondX, pondZ, pondRadius, pondRadius, LAKE_DEPTH_MIN);

        // Outer lakes
        List<int[]> placed = new ArrayList<>();
        int attempts = 0;
        int placed2  = 0;
        while (placed2 < lakeCount && attempts < lakeCount * 20) {
            attempts++;
            double angle = rng.nextDouble() * 2 * Math.PI;
            double dist  = LAKE_MIN_DIST + rng.nextDouble() * (mapRadius - LAKE_MIN_DIST - LAKE_RADIUS_MAX - 50);
            int lx = (int) (Math.cos(angle) * dist);
            int lz = (int) (Math.sin(angle) * dist);

            // Ensure lakes don't overlap
            boolean overlap = false;
            for (int[] p : placed) {
                int dx = p[0] - lx, dz = p[1] - lz;
                if (Math.sqrt(dx * dx + dz * dz) < LAKE_RADIUS_MAX * 3) {
                    overlap = true;
                    break;
                }
            }
            if (overlap) continue;

            int rx    = LAKE_RADIUS_MIN + rng.nextInt(LAKE_RADIUS_MAX - LAKE_RADIUS_MIN + 1);
            int rz    = LAKE_RADIUS_MIN + rng.nextInt(LAKE_RADIUS_MAX - LAKE_RADIUS_MIN + 1);
            int depth = LAKE_DEPTH_MIN  + rng.nextInt(LAKE_DEPTH_MAX  - LAKE_DEPTH_MIN  + 1);
            carveLake(world, lx, lz, rx, rz, depth);
            placed.add(new int[]{lx, lz});
            placed2++;
        }
        log.info("[WaterGenerator] Lakes generated (" + placed2 + " outer + city pond).");
    }

    /**
     * Returns {@code true} when the block column at (x, z) has been marked as water.
     * Used by {@link RoadGenerator} to detect bridge-crossing positions.
     *
     * @param x world X coordinate
     * @param z world Z coordinate
     * @return whether this column contains water
     */
    public boolean isWater(int x, int z) {
        return waterBlocks.contains(encode(x, z));
    }

    // -------------------------------------------------------------------------
    // Internal carving helpers
    // -------------------------------------------------------------------------

    /**
     * Carves a single river from (startX, startZ) toward lower terrain, stopping
     * when it leaves the map or reaches a lake.
     */
    private void carveRiver(World world, int startX, int startZ, int mapRadius, int baseWidth) {
        int x = startX;
        int z = startZ;
        int maxSteps = mapRadius * 3;

        for (int step = 0; step < maxSteps; step++) {
            // Width oscillates along the river
            double warpVal = warpNoise.noise(x * 0.02, z * 0.02);
            int halfW = (baseWidth + (int) (warpVal * 2)) / 2;
            halfW = Math.max(2, halfW);

            int depth = RIVER_DEPTH_MIN + rng.nextInt(RIVER_DEPTH_MAX - RIVER_DEPTH_MIN + 1);

            // Carve a disc of width halfW*2+1 around (x,z)
            for (int dx = -halfW; dx <= halfW; dx++) {
                for (int dz = -halfW; dz <= halfW; dz++) {
                    int wx = x + dx;
                    int wz = z + dz;
                    if (Math.abs(wx) > mapRadius || Math.abs(wz) > mapRadius) continue;

                    double distFromCenter = Math.sqrt(dx * dx + dz * dz);
                    if (distFromCenter > halfW) continue;

                    int surface = terrain.getHeightAt(wx, wz);
                    int waterY  = surface - 1;
                    int bedY    = waterY - depth;

                    try {
                        // Bed: gravel
                        for (int y = bedY; y < waterY; y++) {
                            world.getBlockAt(wx, y, wz).setType(Material.GRAVEL, false);
                        }
                        // Water at surface-1
                        world.getBlockAt(wx, waterY, wz).setType(Material.WATER, false);
                        // Clear above
                        world.getBlockAt(wx, surface, wz).setType(Material.AIR, false);

                        // Sand bank at the rim
                        if (distFromCenter >= halfW - 1) {
                            world.getBlockAt(wx, surface, wz).setType(Material.SAND, false);
                        }

                        waterBlocks.add(encode(wx, wz));
                    } catch (Exception e) {
                        Bukkit.getConsoleSender().sendMessage("§c[WaterGenerator] River carve error at " + wx + "," + wz + ": " + e.getMessage());
                    }
                }
            }

            // Flow: move toward steepest descent, biased by Simplex for meandering
            double nx = warpNoise.noise(x * 0.015 + 1000, z * 0.015);
            double nz = warpNoise.noise(x * 0.015, z * 0.015 + 1000);

            // Compare neighbours to find descending direction
            int bestDX = 0, bestDZ = 0;
            int lowestH = terrain.getHeightAt(x, z);
            int[][] dirs = {{1,0},{-1,0},{0,1},{0,-1}};
            for (int[] d : dirs) {
                int nhX = x + d[0];
                int nhZ = z + d[1];
                if (Math.abs(nhX) > mapRadius || Math.abs(nhZ) > mapRadius) continue;
                int h = terrain.getHeightAt(nhX, nhZ);
                // Add noise bias for meandering
                double bias = (d[0] == 1 ? nx : d[0] == -1 ? -nx : 0)
                            + (d[1] == 1 ? nz : d[1] == -1 ? -nz : 0);
                double effective = h - bias * 1.5;
                if (effective < lowestH) {
                    lowestH = (int) effective;
                    bestDX = d[0];
                    bestDZ = d[1];
                }
            }

            if (bestDX == 0 && bestDZ == 0) break; // flat / local minimum — stop

            x += bestDX;
            z += bestDZ;

            // Stop if we've left the map
            if (Math.abs(x) > mapRadius || Math.abs(z) > mapRadius) break;
        }
    }

    /**
     * Carves a noise-warped ellipse lake centred at (cx, cz).
     *
     * @param world target world
     * @param cx    centre X
     * @param cz    centre Z
     * @param rx    half-radius along X axis
     * @param rz    half-radius along Z axis
     * @param depth lake depth in blocks
     */
    private void carveLake(World world, int cx, int cz, int rx, int rz, int depth) {
        int maxR = Math.max(rx, rz) + 4;

        for (int dx = -maxR; dx <= maxR; dx++) {
            for (int dz = -maxR; dz <= maxR; dz++) {
                int wx = cx + dx;
                int wz = cz + dz;

                // Warp the ellipse boundary with noise
                double warp = warpNoise.noise(wx * 0.04, wz * 0.04) * 0.3;
                double ellipse = ((double) dx / rx) * ((double) dx / rx)
                               + ((double) dz / rz) * ((double) dz / rz);

                if (ellipse > 1.0 + warp) continue;

                int surface = terrain.getHeightAt(wx, wz);
                int waterY  = surface - 1;
                int bedY    = waterY - depth;

                try {
                    // Bed material — mix sand/gravel
                    Material bedMat = (Math.abs(dx + dz) % 2 == 0) ? Material.SAND : Material.GRAVEL;

                    for (int y = bedY; y < waterY; y++) {
                        world.getBlockAt(wx, y, wz).setType(bedMat, false);
                    }
                    world.getBlockAt(wx, waterY, wz).setType(Material.WATER, false);
                    world.getBlockAt(wx, surface, wz).setType(Material.AIR, false);

                    // Sand shore at the rim
                    if (ellipse > 0.75 + warp) {
                        world.getBlockAt(wx, surface, wz).setType(Material.SAND, false);
                    }

                    waterBlocks.add(encode(wx, wz));
                } catch (Exception e) {
                    Bukkit.getConsoleSender().sendMessage("§c[WaterGenerator] Lake carve error at " + wx + "," + wz + ": " + e.getMessage());
                }
            }
        }
    }

    /** Encodes XZ into a single long for O(1) lookup. */
    private static long encode(int x, int z) {
        return ((long) x << 32) | (z & 0xFFFFFFFFL);
    }
}
